"SOC_OUTGOING_PUBLIC_IP_ADDRESS" : "{$SMS_ADDRESS_IP}",
"SD_SNMP_COMMUNITY" : "{$SD->SD_SNMP_COMMUNITY}",
"SOC_SYSLOG_PUBLIC_IP_ADDRESS" : "{$SD->SD_NODE_IP_ADDR}",
"SD_HOSTNAME" : "{$SD->SD_HOSTNAME}",
"SOC_FTP_SERVER_IP_ADDRESS" : "{$FTPSERVER_PUBIP}",
"SITE_LOGIN" : "{$SD->SDID}",
"SITE_PASSWORD" : "{$SD->SD_FTP_PASSWD}"
