#################################################################
#
# file       : Makefile
# Created on : Oct, 16 2012
# Copyright (c) UBIqube Solutions 2012
# 
#################################################################

PHP_SOURCES = $(shell find php -name '*.php' -type f -print)

include ${MAKE_DEFAULT}
