#################################################################
#
# file       : Makefile
# Created on : Sep 13, 2011
# Copyright (c) UBIqube Solutions 2011
# 
#################################################################

PHP_SOURCES = $(shell find php -name '*.php' -type f -print)

include ${MAKE_DEFAULT}
