#################################################################
#
# file       : Makefile
# Created on : 05 Jan 2015
# Copyright (c) UBIqube Solutions 2015
# 
#################################################################

PHP_SOURCES = $(shell find php -name '*.php' -type f -print)

include ${MAKE_DEFAULT}