{if $HA_INTERFACE && $HA_ADDRESS_SLAVE && $HA_MASK}
CONFIG NETWORK INTERFACE ADDRESS ADD ifname={$HA_INTERFACE} address={$HA_ADDRESS_SLAVE} mask={$HA_MASK} AddressComment="HA interface"
{/if}
{if $HA_INTERFACE_SECONDARY && $HA_ADDRESS_SLAVE_SECONDARY && $HA_MASK_SECONDARY}
CONFIG NETWORK INTERFACE ADDRESS ADD ifname={$HA_INTERFACE_SECONDARY} address={$HA_ADDRESS_SLAVE_SECONDARY} mask={$HA_MASK_SECONDARY} AddressComment="HA interface secondary"
{/if}
CONFIG NETWORK ACTIVATE
CONFIG HA JOIN password={$ha_password} ip={$HA_ADDRESS}
CONFIG HA ACTIVATE
