{if $HA_INTERFACE && $HA_ADDRESS && $HA_MASK}
CONFIG NETWORK INTERFACE ADDRESS ADD ifname={$HA_INTERFACE} address={$HA_ADDRESS} mask={$HA_MASK} AddressComment="HA interface"
{/if}
{if $HA_INTERFACE_SECONDARY && $HA_ADDRESS_SECONDARY && $HA_MASK_SECONDARY}
CONFIG NETWORK INTERFACE ADDRESS ADD ifname={$HA_INTERFACE_SECONDARY} address={$HA_ADDRESS_SECONDARY} mask={$HA_MASK_SECONDARY} AddressComment="HA interface secondary"
{/if}
CONFIG NETWORK ACTIVATE
{if $HA_INTERFACE_SECONDARY}
CONFIG HA CREATE password={$ha_password} ifname={$HA_INTERFACE} ifname2={$HA_INTERFACE_SECONDARY}
{else}
CONFIG HA CREATE password={$ha_password} ifname={$HA_INTERFACE}
{/if}
CONFIG HA ACTIVATE
